# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowWaveleter(object):
    def setupUi(self, MainWindowWaveleter):
        MainWindowWaveleter.setObjectName("MainWindowWaveleter")
        MainWindowWaveleter.resize(1092, 850)
        MainWindowWaveleter.setStyleSheet(
            "QPushButton {\n"
            "    border-radius: 5px;\n"
            "    border: 1px solid #ababab;\n"
            "    height: 20px;\n"
            "    background-color: qlineargradient(spread:pad, x1:0.454545, y1:0, x2:0.454545, y2:1, stop:0 rgba(253, 253, 253, 255), stop:1 rgba(239, 239, 239, 255));\n"
            "\n"
            "    \n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "    background: qlineargradient(spread:pad, x1:0.454545, y1:0, x2:0.454545, y2:1, stop:0 rgba(254, 254, 254, 255), stop:1 rgba(248, 248, 248, 255));\n"
            "}"
        )
        self.centralwidget = QtWidgets.QWidget(MainWindowWaveleter)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.verticalLayout.addWidget(self.mdiArea)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.homeButton = QtWidgets.QPushButton(self.frame_3)
        self.homeButton.setObjectName("homeButton")
        self.horizontalLayout.addWidget(self.homeButton)
        self.backButton = QtWidgets.QPushButton(self.frame_3)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout.addWidget(self.backButton)
        self.forwardButton = QtWidgets.QPushButton(self.frame_3)
        self.forwardButton.setObjectName("forwardButton")
        self.horizontalLayout.addWidget(self.forwardButton)
        self.panButton = QtWidgets.QPushButton(self.frame_3)
        self.panButton.setObjectName("panButton")
        self.horizontalLayout.addWidget(self.panButton)
        self.zoomButton = QtWidgets.QPushButton(self.frame_3)
        self.zoomButton.setObjectName("zoomButton")
        self.horizontalLayout.addWidget(self.zoomButton)
        self.configureSubPlots = QtWidgets.QPushButton(self.frame_3)
        self.configureSubPlots.setObjectName("configureSubPlots")
        self.horizontalLayout.addWidget(self.configureSubPlots)
        self.editButton = QtWidgets.QPushButton(self.frame_3)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)
        self.saveButton = QtWidgets.QPushButton(self.frame_3)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindowWaveleter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowWaveleter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1092, 21))
        self.menubar.setObjectName("menubar")
        self.menuSidebar = QtWidgets.QMenu(self.menubar)
        self.menuSidebar.setObjectName("menuSidebar")
        MainWindowWaveleter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowWaveleter)
        self.statusbar.setObjectName("statusbar")
        MainWindowWaveleter.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(MainWindowWaveleter)
        self.dockWidget.setMinimumSize(QtCore.QSize(250, 320))
        self.dockWidget.setMaximumSize(QtCore.QSize(524287, 524287))
        self.dockWidget.setStyleSheet(
            "QDockWidget::title {\n" "    background: #f7f7f7;\n" "}"
        )
        self.dockWidget.setWindowTitle("")
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 230, 767))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setStyleSheet(
            "QFrame {\n"
            "    background-color: #f7f7f7;\n"
            "    border: 1px solid #f0f0f0;\n"
            "}"
        )
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setStyleSheet("QLabel {\n" "    border: None;\n" "}")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.waveletSelector = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.waveletSelector.setFont(font)
        self.waveletSelector.setObjectName("waveletSelector")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.SpanningRole, self.waveletSelector
        )
        self.highFreqLabel = QtWidgets.QLabel(self.frame_2)
        self.highFreqLabel.setStyleSheet("QLabel {\n" "    border: None;\n" "}")
        self.highFreqLabel.setObjectName("highFreqLabel")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.SpanningRole, self.highFreqLabel
        )
        self.highFreqInput = QtWidgets.QLineEdit(self.frame_2)
        self.highFreqInput.setObjectName("highFreqInput")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.SpanningRole, self.highFreqInput
        )
        self.lowFreqLabel = QtWidgets.QLabel(self.frame_2)
        self.lowFreqLabel.setStyleSheet("QLabel {\n" "    border: None;\n" "}")
        self.lowFreqLabel.setObjectName("lowFreqLabel")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.SpanningRole, self.lowFreqLabel
        )
        self.lowFreqInput = QtWidgets.QLineEdit(self.frame_2)
        self.lowFreqInput.setObjectName("lowFreqInput")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.SpanningRole, self.lowFreqInput
        )
        self.labelf3 = QtWidgets.QLabel(self.frame_2)
        self.labelf3.setStyleSheet("QLabel {\n" "    border: None;\n" "}")
        self.labelf3.setObjectName("labelf3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.labelf3)
        self.frequency3Input = QtWidgets.QLineEdit(self.frame_2)
        self.frequency3Input.setObjectName("frequency3Input")
        self.formLayout.setWidget(
            7, QtWidgets.QFormLayout.SpanningRole, self.frequency3Input
        )
        self.labelf4 = QtWidgets.QLabel(self.frame_2)
        self.labelf4.setStyleSheet("QLabel {\n" "    border: None;\n" "}")
        self.labelf4.setObjectName("labelf4")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.labelf4)
        self.frequency4Input = QtWidgets.QLineEdit(self.frame_2)
        self.frequency4Input.setObjectName("frequency4Input")
        self.formLayout.setWidget(
            9, QtWidgets.QFormLayout.SpanningRole, self.frequency4Input
        )
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setStyleSheet("QLabel {\n" "    border: None;\n" "}")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.label_4)
        self.samplesInput = QtWidgets.QLineEdit(self.frame_2)
        self.samplesInput.setObjectName("samplesInput")
        self.formLayout.setWidget(
            11, QtWidgets.QFormLayout.SpanningRole, self.samplesInput
        )
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setStyleSheet("QLabel {\n" "    border: None;\n" "}")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.label_5)
        self.timeInput = QtWidgets.QLineEdit(self.frame_2)
        self.timeInput.setObjectName("timeInput")
        self.formLayout.setWidget(
            13, QtWidgets.QFormLayout.SpanningRole, self.timeInput
        )
        self.plotWavButton = QtWidgets.QPushButton(self.frame_2)
        self.plotWavButton.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plotWavButton.setFont(font)
        self.plotWavButton.setObjectName("plotWavButton")
        self.formLayout.setWidget(
            14, QtWidgets.QFormLayout.SpanningRole, self.plotWavButton
        )
        self.horizontalLayout_4.addLayout(self.formLayout)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindowWaveleter.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionViewSideBar = QtWidgets.QAction(MainWindowWaveleter)
        self.actionViewSideBar.setObjectName("actionViewSideBar")
        self.menuSidebar.addAction(self.actionViewSideBar)
        self.menubar.addAction(self.menuSidebar.menuAction())

        self.retranslateUi(MainWindowWaveleter)
        QtCore.QMetaObject.connectSlotsByName(MainWindowWaveleter)
        MainWindowWaveleter.setTabOrder(self.highFreqInput, self.lowFreqInput)
        MainWindowWaveleter.setTabOrder(self.lowFreqInput, self.frequency3Input)
        MainWindowWaveleter.setTabOrder(self.frequency3Input, self.frequency4Input)
        MainWindowWaveleter.setTabOrder(self.frequency4Input, self.samplesInput)
        MainWindowWaveleter.setTabOrder(self.samplesInput, self.timeInput)
        MainWindowWaveleter.setTabOrder(self.timeInput, self.plotWavButton)
        MainWindowWaveleter.setTabOrder(self.plotWavButton, self.homeButton)
        MainWindowWaveleter.setTabOrder(self.homeButton, self.backButton)
        MainWindowWaveleter.setTabOrder(self.backButton, self.forwardButton)
        MainWindowWaveleter.setTabOrder(self.forwardButton, self.panButton)
        MainWindowWaveleter.setTabOrder(self.panButton, self.zoomButton)
        MainWindowWaveleter.setTabOrder(self.zoomButton, self.configureSubPlots)
        MainWindowWaveleter.setTabOrder(self.configureSubPlots, self.editButton)
        MainWindowWaveleter.setTabOrder(self.editButton, self.saveButton)
        MainWindowWaveleter.setTabOrder(self.saveButton, self.waveletSelector)
        MainWindowWaveleter.setTabOrder(self.waveletSelector, self.scrollArea)

    def retranslateUi(self, MainWindowWaveleter):
        _translate = QtCore.QCoreApplication.translate
        MainWindowWaveleter.setWindowTitle(
            _translate("MainWindowWaveleter", "Waveleter")
        )
        self.homeButton.setStatusTip(
            _translate("MainWindowWaveleter", "Reset original view")
        )
        self.homeButton.setText(_translate("MainWindowWaveleter", "Home"))
        self.backButton.setStatusTip(
            _translate("MainWindowWaveleter", "Back to previous view")
        )
        self.backButton.setText(_translate("MainWindowWaveleter", "Back"))
        self.forwardButton.setStatusTip(
            _translate("MainWindowWaveleter", "Forward to next view")
        )
        self.forwardButton.setText(_translate("MainWindowWaveleter", "Forward"))
        self.panButton.setStatusTip(
            _translate(
                "MainWindowWaveleter",
                "Left buttons pans, Right button zooms x/y fixes axis, CTRL fixes aspect",
            )
        )
        self.panButton.setText(_translate("MainWindowWaveleter", "Pan"))
        self.zoomButton.setStatusTip(
            _translate("MainWindowWaveleter", "Zoom to rectangle x/y fixes axis")
        )
        self.zoomButton.setText(_translate("MainWindowWaveleter", "Zoom"))
        self.configureSubPlots.setStatusTip(
            _translate("MainWindowWaveleter", "Configure subplots")
        )
        self.configureSubPlots.setText(_translate("MainWindowWaveleter", "Configure"))
        self.editButton.setStatusTip(
            _translate("MainWindowWaveleter", "Edit axis, curve and image parameters")
        )
        self.editButton.setText(_translate("MainWindowWaveleter", "Edit"))
        self.saveButton.setStatusTip(
            _translate("MainWindowWaveleter", "Save the figure")
        )
        self.saveButton.setText(_translate("MainWindowWaveleter", "Save"))
        self.menuSidebar.setTitle(_translate("MainWindowWaveleter", "View"))
        self.label.setText(
            _translate(
                "MainWindowWaveleter",
                '<html><head/><body><p align="center"><span style=" font-size:12pt; font-weight:600;">Wavelet</span></p></body></html>',
            )
        )
        self.waveletSelector.setStatusTip(
            _translate(
                "MainWindowWaveleter", "Choose between differents wavelets to plot"
            )
        )
        self.highFreqLabel.setText(
            _translate(
                "MainWindowWaveleter",
                '<html><head/><body><p align="center"><span style=" font-size:12pt;">High Frequency</span></p></body></html>',
            )
        )
        self.highFreqInput.setToolTip(
            _translate(
                "MainWindowWaveleter",
                "Enter the high frequency or peak frequency of your wavelet",
            )
        )
        self.lowFreqLabel.setText(
            _translate(
                "MainWindowWaveleter",
                '<html><head/><body><p align="center"><span style=" font-size:12pt;">Low Frequency</span></p></body></html>',
            )
        )
        self.lowFreqInput.setToolTip(
            _translate("MainWindowWaveleter", "Enter the low frequency, if needed")
        )
        self.labelf3.setText(
            _translate(
                "MainWindowWaveleter",
                '<html><head/><body><p align="center"><span style=" font-size:12pt;">High Cutoff Frequency</span></p></body></html>',
            )
        )
        self.labelf4.setText(
            _translate(
                "MainWindowWaveleter",
                '<html><head/><body><p align="center"><span style=" font-size:12pt;">Low Cutoff Frequency</span></p></body></html>',
            )
        )
        self.label_4.setText(
            _translate(
                "MainWindowWaveleter",
                '<html><head/><body><p align="center"><span style=" font-size:12pt;">Samples</span></p></body></html>',
            )
        )
        self.label_5.setText(
            _translate(
                "MainWindowWaveleter",
                '<html><head/><body><p align="center"><span style=" font-size:12pt;">Time (ms)</span></p></body></html>',
            )
        )
        self.plotWavButton.setText(_translate("MainWindowWaveleter", "Plot"))
        self.actionViewSideBar.setText(_translate("MainWindowWaveleter", "Sidebar"))
